# 定数宣言

DEFAULT_TRANSLATION_VERSION = "0"
DEFAULT_APP_VERSION = "100"
DEFAULT_SERVER_URL = "http://sample.co/ps2/"
DEFAULT_LOCAL_PATH = ""
DEFAULT_LAST_UPDATE = "2000/1/1 00:00"
DEFAULT_LAUNCH_MODE = 1

WINDOW_TITLE = "PS2日本語翻訳ツール"
LAUNCH_BUTTON_TEXT = "起動"
REPLACE_BUTTON_TEXT = "ファイル置換"
UPDATE_BUTTON_TEXT = "アップデート"
LOCAL_PATH_BUTTON_TEXT = "ローカルファイル変更"
URL_CHANGE_BUTTON_TEXT = "URL変更"
NORMAL_RADIO_TEXT = "通常起動"
STEAM_RADIO_TEXT = "Steam経由起動"
VERSION_LABEL_TEXT = "Version\nアプリケーション：{app}\n翻訳データ：{tran}"
ERROR_MESSAGE = "エラー"
REPLACE_COMPLETE_MESSAGE = "ファイル置き換えが完了しました。"
UPDATE_COMPLETE_MESSAGE = "アップデート完了後「ファイル置換」を押してください"
LOCAL_PATH_SELECTED_MESSAGE = "{selected_path}が選択されました"
SERVER_DOWN_MESSAGE = "ただいまサーバが落ちております。\n更新が利用できません。\n{local_path}\nエラーコード: {server_code}"
LATEST_VERSION_MESSAGE = "最新版です\nアドレス：{local_path}"
UPDATE_AVAILABLE_MESSAGE = "更新があります"
EXEC_FILE_NOT_FOUND_MESSAGE = "実行ファイルが見つかりません"
SETTING_REQUIRED_MESSAGE = "設定を行い、ローカルファイルのアドレスを変更してください"
SELECT_VALUE_MESSAGE = "値を選択してください"
USAGE_ERROR_MESSAGE = "使い方が異なります"
FILE_COPY_FAILED_MESSAGE = "ファイルのコピーに失敗しました: {e}"
APP_UPDATE_MESSAGE = "本体の更新があります"
CONFIRM_BROWSER_LAUNCH_MESSAGE = "ブラウザを起動しますか？"

SERVER_URL = "http://sample.co/ps2/ps2.html"
DOWNLOAD_FAILED_MESSAGE = "ファイルのダウンロードに失敗しました"
UPDATE_UNAVAILABLE_MESSAGE = "アップデートはご利用できません"
DOWNLOADING_TRANSLATION_DATA_MESSAGE = "{index}/3の翻訳データをダウンロード中"
TRANSLATION_DATA_UPDATED_MESSAGE = "翻訳データを更新しました"

URL_CHANGE_DIALOG_TITLE = "URL変更"
URL_LABEL = "URL:"
OK_BUTTON_TEXT = "確定"
DEFAULT_BUTTON_TEXT = "デフォルトに戻す"
DEFAULT_URL = "http://sample.co/ps2/"
STEAM_GAME_URI = "steam://rungameid/218230"
